### ISSUE TITLE
Checksum discrepancy on Clojars

### ISSUE THREAD

**Issue by joshuamiller** [neatonk/clj-aws-auth#1]
When trying to build a project with clj-aws-auth 0.1.0:

```
$ lein deps
Retrieving clj-aws-auth/clj-aws-auth/0.1.0/clj-aws-auth-0.1.0.pom from clojars
Retrieving clj-aws-auth/clj-aws-auth/0.1.0/clj-aws-auth-0.1.0.pom from clojars
Could not transfer artifact clj-aws-auth:clj-aws-auth:pom:0.1.0 from/to clojars (https://clojars.org/repo/): Checksum validation failed, expected 374b212313b073f8cc89900c28e65aa76c7e8dd8 but is 471dec142fd399757ff0cc24a24b262a4624e74a
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

I'm not sure at what layer these checksums are generated, maybe simply re-pushing to Clojars would work? I'm happy to help any way I can.

**Comment by cmackie21** [comment]
Why is this still not resolved after 5 years, this jar isn't even on clojars anymore.  This library looked like it was going to do exactly what we needed and because of the above issue it isn't possible to use.

**Comment by neatonk** [comment]
Hi @cmackie21, this project is not under active development and has not been updated or released since 2013. I have no plans to resume work on this project and will archive it shortly. Anyone interested in reviving this project is welcome to do so by creating a fork.
